MAIN_URL = 'https://qa-scooter.praktikum-services.ru'
LOGIN_COURIER_URL = MAIN_URL + '/api/v1/courier/login'
CREATE_COURIER_URL = MAIN_URL + '/api/v1/courier'
CREATE_ORDER_URL = MAIN_URL + '/api/v1/orders'
GET_ORDER_LIST_URL = MAIN_URL + '/api/v1/orders'
DELETE_COURIER_URL = MAIN_URL + '/api/v1/courier/{courier_id}'
ACCEPT_ORDER_URL = MAIN_URL + '/api/v1/orders/accept/{order_id}'
GET_ORDER_BY_TRACK_NUMBER_URL = MAIN_URL + '/api/v1/orders/track'
